name: Prod CI to Docker Hub - MultiArch

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '30 5 * * 1,3'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Lower github-runner storage
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./requirements/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nasanccs/tensorflow-caney:latest
